
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g history-limit 100000
set -g mouse on 
set -g set-clipboard on
setw -g mode-keys vi

set -g base-index 1 # start windows numbering at 1

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Style

# don't rename windows automatically
set-option -g allow-rename off

# More colors
set -g default-terminal "tmux-256color"


# Status line colors
set-option -g status-style 'fg=#95C72A bg=default'


# clock mode
setw -g clock-mode-colour "#229986"

# copy mode
setw -g mode-style 'fg=black bg=#95C72A bold'

# panes
set -g pane-border-style 'fg=#95C72A'
set -g pane-active-border-style 'fg=#229986'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#95C72A'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=#161A19 fg=#229986'
set -g status-right-length 50

setw -g window-status-current-style 'fg=#161A19 bg=#95C72A'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=#95C72A bg=#161A19'
setw -g window-status-format ' #I #[fg=white]#W #[fg=#229986]#F '

setw -g window-status-bell-style 'fg=#229986 bg=#95C72A bold'

# messages
set -g message-style 'fg=#161A19 bg=#229986 bold'


# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
